#!/bin/bash
# Setup cron job for daily authority sync

set -e

echo "🕐 Setting up daily authority sync cron job..."

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Backend URL (adjust for production)
BACKEND_URL="${BACKEND_URL:-http://localhost:8000}"
API_ENDPOINT="${BACKEND_URL}/api/v1/sync/authorities/scheduled"

# Generate or use existing API key
API_KEY="${SYNC_API_KEY:-change_me_in_production}"

echo -e "${BLUE}Backend URL:${NC} $BACKEND_URL"
echo -e "${BLUE}API Endpoint:${NC} $API_ENDPOINT"

# Create cron job script
CRON_SCRIPT="/usr/local/bin/sync-authorities.sh"

echo -e "${BLUE}Creating cron script:${NC} $CRON_SCRIPT"

sudo tee $CRON_SCRIPT > /dev/null <<EOF
#!/bin/bash
# Daily authority sync from DDR Archive GraphQL
# Generated by setup-cron-sync.sh

LOGFILE="/var/log/authority-sync.log"

echo "\$(date '+%Y-%m-%d %H:%M:%S') - Starting scheduled authority sync" >> \$LOGFILE

curl -X POST \\
  -H "X-API-Key: $API_KEY" \\
  -H "Content-Type: application/json" \\
  -s \\
  "$API_ENDPOINT" \\
  >> \$LOGFILE 2>&1

if [ \$? -eq 0 ]; then
    echo "\$(date '+%Y-%m-%d %H:%M:%S') - Sync completed successfully" >> \$LOGFILE
else
    echo "\$(date '+%Y-%m-%d %H:%M:%S') - Sync failed with exit code \$?" >> \$LOGFILE
fi

# Keep only last 1000 lines of log
tail -n 1000 \$LOGFILE > \$LOGFILE.tmp && mv \$LOGFILE.tmp \$LOGFILE
EOF

sudo chmod +x $CRON_SCRIPT

echo -e "${GREEN}✓${NC} Created executable cron script"

# Add to crontab if not already present
CRON_LINE="0 2 * * * $CRON_SCRIPT"

# Check if cron job already exists
if crontab -l 2>/dev/null | grep -q "sync-authorities.sh"; then
    echo -e "${YELLOW}⚠${NC}  Cron job already exists, skipping..."
else
    # Add to crontab
    (crontab -l 2>/dev/null; echo "$CRON_LINE") | crontab -
    echo -e "${GREEN}✓${NC} Added cron job: Daily at 2:00 AM"
fi

# Create log file
sudo touch /var/log/authority-sync.log
sudo chmod 666 /var/log/authority-sync.log

echo ""
echo -e "${GREEN}✨ Cron setup complete!${NC}"
echo ""
echo "Schedule: Daily at 2:00 AM"
echo "Log file: /var/log/authority-sync.log"
echo ""
echo "View cron jobs:"
echo "  crontab -l"
echo ""
echo "View sync log:"
echo "  tail -f /var/log/authority-sync.log"
echo ""
echo "Manual trigger:"
echo "  $CRON_SCRIPT"
echo ""
echo -e "${YELLOW}⚠ For production:${NC}"
echo "  1. Set SYNC_API_KEY environment variable"
echo "  2. Update BACKEND_URL for production domain"
echo "  3. Secure API key in secrets management"
